export const archaivedData = [
  {
    imageFileName: "static/images/portfolio/2025/lovestories.jpg",
    imageFileNameDetail: "static/images/portfolio/2025/lovestories.jpg",
    header: "ラブ・ストーリー【3rd concert】",
    subheader: "女声合唱組曲",
    content: "やなせ　たかし/鈴木　憲夫/坂村　真民作詩・鈴木　憲夫作曲",
    extraInfo: "五月の森 / ねこ物語 / 昼の月 / 永遠の一日",
    extraInfo2: "ラブ・ストーリー　朗読：古谷小枝子",
  },
  {
    imageFileName: "static/images/portfolio/cuisine-thumb.webp",
    imageFileNameDetail: "static/images/portfolio/cuisine-full.webp",
    header: "キュイジーヌ I ・II【3rd concert】",
    subheader: "女声(児童)のための合唱曲",
    content: "伊藤　千鶴作詩・吉岡　弘行作曲",
    extraInfo: "パエリア / インド風チキンカレー / 大阪風お好み焼き /  杏仁豆腐(キュイジーヌ II)",
    extraInfo2: "",
  },
  {
    imageFileName: "static/images/portfolio/01-thumb.jpg",
    imageFileNameDetail: "static/images/portfolio/01-full.jpg",
    header: "桜の花びらのように【3rd concert】",
    subheader: "女声合唱とピアノのための組曲",
    content: "みなづきみのり作詩・田中達也作曲",
    extraInfo: "レモンイエローの夏 / 十月 / 間奏曲 / 桜の花びらのように",
    extraInfo2: "",
  },
  {
    imageFileName: "static/images/portfolio/02-thumb.webp",
    imageFileNameDetail: "static/images/portfolio/02-full.webp",
    header: "愛する歌",
    subheader: "女声合唱アルバム【2nd concert】",
    content: "やなせ たかし作詞・木下牧子作曲",
    extraInfo: "ひばり / ロマンチストの豚 / 海と涙と私と / ユレル / さびしいカシの木 / きんいろの太陽がもえる朝に",
    extraInfo2:
      "2023年第2回コンサートでお届けしました。全１０曲から星野敦子先生が厳選した６曲の心の旅。ポレポーレのYouTubeに音源があります。",
  },
  {
    imageFileName: "static/images/portfolio/03-thumb.webp",
    imageFileNameDetail: "static/images/portfolio/03-full.webp",
    header: "青春歌年鑑２００８",
    subheader: "昭和歌謡メドレー【2nd concert】",
    content: "Arranged by Junko Yokoyama✨",
    extraInfo:
      "2023年第2回コンサートでお届けしました。在る日突然 / 恋の季節 / ヴァケイション / ブルー・ライト・ヨコハマ / 夜明けのスキャット / また逢う日まで",
    extraInfo2: "地域のお祭り、定期演奏会にて、「元気をもらった✨」と好評をいただいております。",
  },
  {
    imageFileName: "static/images/portfolio/2023/三つの不思議な仕事.webp",
    imageFileNameDetail: "static/images/portfolio/2023/三つの不思議な仕事.webp",
    header: "三つの不思議な仕事",
    subheader: "女声合唱曲集【2nd concert】",
    content: "池澤　夏樹作詞・池辺　晋一郎作曲",
    extraInfo: "空みがき / 明日つくり / 夢売り",
    extraInfo2: "2023年第2回コンサートでお届けしました。",
  },
  {
    imageFileName: "static/images/portfolio/2021/yokatta.jpg",
    imageFileNameDetail: "static/images/portfolio/2021/yokatta.jpg",
    header: "よかったなあ",
    subheader: "女声合唱組曲【1st concert】",
    content: "まど　みちお作詞・なかにし　あかね作曲",
    extraInfo: "よかったなあ / たんぽぽ / 小鳥たち / ケヤキ",
    extraInfo2: "2021年第1回コンサートでお届けしました。",
  },
  {
    imageFileName: "static/images/portfolio/2021/sound-of-music.jpg",
    imageFileNameDetail: "static/images/portfolio/2021/sound-of-music.jpg",
    header: "The Sound Of Music",
    subheader: "女声合唱組曲【1st concert】",
    content: "Arranged by Junko Yokoyama✨",
    extraInfo:
      "サウンドオブミュージック / 朝の讃美歌 / もうすぐ17才 / ひとりぼっちの山羊使い / ドレミの歌 / エーデルワイス / すべての山にのぼれ",
    extraInfo2: "2021年第1回コンサートでお届けしました。",
  },
  {
    imageFileName: "static/images/portfolio/2021/いつの日か.jpg",
    imageFileNameDetail: "static/images/portfolio/2021/いつの日か.jpg",
    header: "いつの日か",
    subheader: "女声合唱のための童謡メドレー【1st concert】",
    content: "源田　俊一郎編曲",
    extraInfo:
      "しゃぼん玉 / 揺籠の歌 / 叱られて / 七つの子 / 夕焼小焼 / 月の砂漠 / 証城寺の狸囃子 / 汽車の歌 / みかんの花咲く丘 / どんぐりころころ / 郷の秋 / あの町この町 / 赤とんぼ",
    extraInfo2: "2021年第1回コンサートでお届けしました。",
  },
  {
    imageFileName: "static/images/portfolio/2021/ふるさと.jpg",
    imageFileNameDetail: "static/images/portfolio/2021/ふるさと.jpg",
    header: "ふるさとの四季",
    subheader: "女声合唱のための唱歌メドレー",
    content: "源田　俊一郎編曲",
    extraInfo:
      "故郷 / 春の小川 / 朧月夜 / 鯉のぼり / 茶摘 / 夏は来ぬ / われは海の子 / 村祭 / 紅葉 / 冬景色 / 雪 / 故郷",
    extraInfo2: "ホームなどへの慰問で歌わさせていただいています。",
  },
];
